name: metacreative
favicon: null
layout_spectrum: 1
typography_spectrum: 0.6297260650899261
title: Web Design Perth
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#58585a'
    - '#009de0'
    - '#a6a6a8'
    - '#86cbeb'
  brandStrength: 1
  lightness: 0.9887805813923478
  saturation: 0.05240963096730411
  rhythmicContrast: 0.756812155013904
purpose: []
